namespace Microsoft.MediaCenter.TV.Tuners;

public enum CPEvents
{
	CPEVENT_PROTECTWINDOWED = 9,
	CPEVENT_UNTRUSTEDGRAPH = 8,
	CPEVENT_STUBLIB = 7,
	CPEVENT_DOWNRES = 6,
	CPEVENT_SAC = 5,
	CPEVENT_ROLLBACK = 4,
	CPEVENT_LICENSE = 3,
	CPEVENT_COPP = 2,
	CPEVENT_RATINGS = 1,
	CPEVENT_NONE = 0
}
